app:
  env: "local"
  port: "8000"
redis:
  host: "127.0.0.1"
  port: 6379
  db: 6
urls:
  idcade: "https://aip.baidubce.com/rest/2.0/ocr/v1/idcard"
  verify: "https://aip.baidubce.com/rest/2.0/face/v3/person/verify"
  type: "client_credentials"
  apiKey: "eWk7VQDLdoyGfrnuXdkObkv4"
  secretKey: "LRh3iMsp6GG8p3hwoB1cLbgcEtfTACrs"
  imageUrl: "https://www.zgtest.club/api/image/upload"
  gatewayUrl: "http://www.zgtest.club/api/v2/user/refresh_account_info"
