conn_max_idle: 10 # 通用配置，连接池最大空闲连接数
conn_max_open: 100 # 通用配置，连接池最大连接数
conn_max_lifetime: 1h # 通用配置，连接数最大生命周期
protocol: tcp # 通用配置，传输协议
loc: Local # 通用配置，时区

default:
    driver: mysql # 连接驱动
    dsn: "" # dsn，如果设置了dsn, 以下的所有设置都不生效
    host: localhost # ip地址
    port: 3306 # 端口
    database: bbs # 数据库
    username: jianfengye # 用户名
    password: "123456789" # 密码
    charset: utf8mb4 # 字符集
    collation: utf8mb4_unicode_ci # 字符序
    timeout: 10s # 连接超时
    read_timeout: 2s # 读超时
    write_timeout: 2s # 写超时
    parse_time: true # 是否解析时间
    protocol: tcp # 传输协议
    loc: Local # 时区


# MySQL 数据库相关配置
db:
    host: 127.0.0.1  # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
    username: miniblog # MySQL 用户名(建议授权最小权限集)
    password: miniblog1234 # MySQL 用户密码
    database: miniblog # miniblog 系统所用的数据库名
    max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
    max-open-connections: 100 # MySQL 最大打开的连接数，默认 100
    max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
