app:
  env: "local"
  port: "8000"
redis:
  host: "tx4-inno-mido-testdb01.bj"
  password: "a)jEEctmup18"
  port: 6379
  db: 0

urls:
  balance: "https://www.zgtest.club/api/v2/user/balance"
  config: "https://www.zexchange.xyz/api/wallet/v1/currency/config"